version: "3.3"

networks:
  # docker internal network
  lempnet:
    driver: bridge

services:

  # LEMP Server from image
  app:
    image: lemp-dev:latest
    container_name: laravelwebapp
    #restart: unless-stopped
    env_file:
      - .env
    #command: bash -c "set >> /etc/environment"  
    #command: sh -c set >> /etc/environment
    #command: bash -c echo "g"
    working_dir: /var/www/html/
    ports:
        - 80:80    
        - 443:443
    volumes:
      - ../www:/var/www/html/
    networks:
      - lempnet
    tty: true
    #entrypoint: ["sh", "-c", "set"]
    #command: ["sh", "-c", "set"]
    #command: ["sh", "-c", "set"]
    #command: ["sh", "-c", "tail -f /dev/null"]
